<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>s</string>
	</array>
	<key>name</key>
	<string>NIOS II ASM</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(?=(\.equ|\.global)\s*[\w0-9_]*)</string>
			<key>end</key>
			<string>&lt;&lt;EOF&gt;&gt;|
|,|(?=#)</string>
			<key>name</key>
			<string>preprocessor.assignment</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(\.equ|\.global)</string>
					<key>name</key>
					<string>keyword.control.instruction</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[\w0-9_]*</string>
					<key>name</key>
					<string>entity.name.function.label</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>(^|\s)(add|addi|and|andhi|andi|beq|bge|bgeu|bgt|bgtu|ble|bley|blt|bleu|bltu|bne|break|bret|callr|cmpeq|cmpeqi|cmepge|cmpge|cmpgei|cmpgeu|cmpgeui|cmpgti|cmpgtu|cmpeu|cmpgt|cmgti|cmpgtui|cmplei|cmple|cmpleu|cmpleui|cmplt|cmplti|cmpltu|cmpltui|cmpne|cmpnei|custom|div|divu|eret|flushd|flushda|flushi|flushp|initd|initda|initi|jmp|ldb|ldbio|ldbu|ldbuio|ldh|ldhio|ldhu|ldhuio|ldw|ldwio|mov|movhi|movi|movia|movui|mul|muli|mulxss|mulxsu|mulxuu|nextpc|nop|nor|or|orhi|ori|rdprs|rdctl|rdprc|ret|rol|roli|ror|sll|slli|sra|srai|srl|srli|stb|stbio|sth|sthio|stw|stwio|sub|subi|sync|trap|wrctl|wrprs|xor|xorhi|xori|ret)(\s|
|&lt;&lt;EOF&gt;&gt;)</string>
			<key>name</key>
			<string>keyword.control.instruction</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(^|\s)(?=(jmpi|br|call)[\s]\w*)</string>
			<key>end</key>
			<string>$|
|(?=#)|[^\w\s_]</string>
			<key>name</key>
			<string>instruction_addr_immediate</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>(jmpi|br|call)</string>
					<key>name</key>
					<string>keyword.control.instruction</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=\s)\w*</string>
					<key>name</key>
					<string>entity.name.function.label</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?=[0-9\w_]*\((r[0-9]+|bt|gp|sp|fp|ea|sstatus|ra)\))</string>
			<key>end</key>
			<string>(?&lt;=\))</string>
			<key>name</key>
			<string>deref</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[0-9\w_]*(?=\()</string>
					<key>name</key>
					<string>constant.numeric.offset.niosii</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\(|\)</string>
					<key>name</key>
					<string>constant.numeric.offset.control.paren</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>[0-9a-zA-Z|_]*:</string>
			<key>name</key>
			<string>entity.name.function.label</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>#</string>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>comment.line.niosii</string>
			<key>patterns</key>
			<array/>
		</dict>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.niosii</string>
			<key>patterns</key>
			<array/>
		</dict>
		<dict>
			<key>begin</key>
			<string>.(?=-?0x[0-9a-fA-F])</string>
			<key>end</key>
			<string>[^0-9\-xa-fA-F]</string>
			<key>name</key>
			<string>numeric.hex.niosii</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\-]</string>
					<key>name</key>
					<string>keyword.control.hex.numeric</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>match</key>
					<string>[x0-9a-fA-F]</string>
					<key>name</key>
					<string>constant.numeric</string>
					<key>patterns</key>
					<array/>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>[\s\(](?=-?[0-9])</string>
			<key>end</key>
			<string>[^0-9]</string>
			<key>name</key>
			<string>numeric.niosii</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[\-]</string>
					<key>name</key>
					<string>keyword.control.hex.numeric</string>
					<key>patterns</key>
					<array/>
				</dict>
				<dict>
					<key>match</key>
					<string>[0-9]</string>
					<key>name</key>
					<string>constant.numeric</string>
					<key>patterns</key>
					<array/>
				</dict>
			</array>
		</dict>
	</array>
	<key>repository</key>
	<dict/>
	<key>scopeName</key>
	<string>source.niosii</string>
	<key>uuid</key>
	<string>07629b98-022c-4204-a227-aa65ae352faa</string>
</dict>
</plist>
